### ISSUE TITLE
Julian's biography

### ISSUE THREAD

**Issue by qiyunzhu** [qiyunlab/qiyunlab.github.io#3]
Hello Julian, we have a lab website at: https://qiyunlab.github.io/. The [people](https://qiyunlab.github.io/people) page is to showcase a list of lab members. @droush has already added his information. It is your turn now! Feel free to submit a pull request which includes a biography of you as well as any modification to the entire website as you like. Daniel's [pull request](https://github.com/qiyunzhu/qiyunlab.github.io/pull/1) is a good example for you. Specifically, you will need to edit [people.md](https://github.com/qiyunlab/qiyunlab.github.io/blob/master/people.md). This is a [GitHub Markdown](https://guides.github.com/features/mastering-markdown/) file, with a [Jekyll front matter](https://jekyllrb.com/docs/front-matter/). Feel free to ask me or Daniel any questions!

**Comment by yujulian0168** [comment]
Hello Qiyun, I have just submitted my pull request to edit by bio. Reading through the comments on Dan's pull request was very helpful.

**Comment by qiyunzhu** [comment]
@yujulian0168 Thank you! Please find my review.
